### ISSUE TITLE
Dockerfile not building

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fetpapiClient#6]
Error with `docker build` command:

> 
> Resolving apache.mirrors.benatherton.com (apache.mirrors.benatherton.com)... failed: Name or service not known.
> wget: unable to resolve host address 'apache.mirrors.benatherton.com'
> 

Can be resolved by replacing the error link with the official archive:

> http://archive.apache.org/dist/avro/avro-1.10.1/cpp/avro-cpp-1.10.1.tar.gz

**Comment by philippeVerney** [comment]
Good catch.
Thank you
